name: 'nixpkgs-health-check-action'
description: 'Check packages are buildable and up-to-date'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  pnames:
    description: 'per line or ", " delimited if multiple'
    required: true

runs:
  using: 'composite'
  steps:
    - run: | # zizmor: ignore[template-injection]
        nix run 'github:NixOS/nixpkgs/nixpkgs-unstable#hydra-check' -- ${{ inputs.pnames }}
        nix run 'github:kachick/nixpkgs-update-log-checker' -- --packages ${{ inputs.pnames }}
      shell: bash
