name: 'Nixpkgs Health Check'
description: 'Checks the health of a Nixpkgs package using hydra-check and nixpkgs-update logs'
inputs:
  pname:
    description: 'Package name in Nixpkgs'
    required: true
  hydra:
    description: 'Whether to run Hydra check'
    default: 'true'
    required: false
  nixpkgs-update:
    description: 'Whether to run nixpkgs-update check'
    default: 'true'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run hydra-check
      if: inputs.hydra == 'true'
      shell: bash
      env:
        PNAME: ${{ inputs.pname }}
      run: |
        nix run .#nixpkgs-health-check-hydra -- "$PNAME"

    - name: Run nixpkgs-update-log-checker
      if: inputs.nixpkgs-update == 'true'
      shell: bash
      env:
        PNAME: ${{ inputs.pname }}
      run: |
        nix develop --command nixpkgs-update-log-checker --packages "$PNAME"
