# Configuration for nixpkgs-health-check-action

[skip]
pinact = { nixpkgs-update = "Failing in nixpkgs-update, see issue #..." }
shogihome = { nixpkgs-update = "Failing in nixpkgs-update, see issue #..." }
typescript-go = { nixpkgs-update = "Failing in nixpkgs-update, see issue #..." }

# For testing
hello = { hydra = "Test skip", nixpkgs-update = "Test skip" }
