# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      # Unit tests
      - nix eval --json --file test-check-skip.nix
      # Integration-like tests (Verify GHA usage pattern)
      - |
          result=$(PNAME=hello nix eval --impure --json --expr '(import ./check-skip.nix { pname = builtins.getEnv "PNAME"; service = "hydra"; })')
          echo "$result" | grep -q '"skip":true'
      - |
          result=$(PNAME=biz-ud-gothic nix eval --impure --json --expr '(import ./check-skip.nix { pname = builtins.getEnv "PNAME"; service = "hydra"; })')
          echo "$result" | grep -q '"skip":false'
  fmt:
    cmds:
      - dprint fmt
      - nix fmt
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - zizmor .
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
      - git ls-files | xargs nix run github:kachick/selfup/v1.3.0 -- list -check
  selfup:
    cmds:
      - git ls-files | xargs nix run github:kachick/selfup/v1.3.0 -- run
