# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      # Unit tests
      - nix eval --json --file pkgs/check-skip/test.nix
      - pkgs/nixpkgs-health-check-hydra/test.bash
      # Integration-like tests (Verify GHA usage pattern)
      - nix run .#check-skip -- --pname "hello" --service "hydra" | grep -q '"skip":true'
      - nix run .#check-skip -- --pname "biz-ud-gothic" --service "hydra" | grep -q '"skip":false'
  fmt:
    cmds:
      - dprint fmt
      - nix fmt
      - git ls-files '*.bash' | xargs shfmt -w
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - zizmor .
      - gitleaks dir . --verbose
      - git ls-files '*.bash' | xargs shellcheck
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
