# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      # Unit tests
      - nix eval --json --file test-check-skip.nix
      # Integration-like tests (Verify GHA usage pattern)
      - ./check-skip.bash --pname "hello" --service "hydra" --config "nixpkgs-health-check.toml" | grep -q '"skip":true'
      - ./check-skip.bash --pname "biz-ud-gothic" --service "hydra" --config "nixpkgs-health-check.toml" | grep -q '"skip":false'
  fmt:
    cmds:
      - dprint fmt
      - nix fmt
      - shfmt -w check-skip.bash
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - zizmor .
      - shellcheck check-skip.bash
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
      - git ls-files | xargs nix run github:kachick/selfup/v1.3.0 -- list -check
  selfup:
    cmds:
      - git ls-files | xargs nix run github:kachick/selfup/v1.3.0 -- run
