name: 'Nixpkgs Update Check'
description: 'Checks the health of a Nixpkgs package using nixpkgs-update logs'
inputs:
  pname:
    description: 'Package name in Nixpkgs'
    required: true
  config:
    description: 'Path to the skip-list configuration file'
    default: 'nixpkgs-health-check.toml'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Check skip status
      id: check-skip
      shell: bash
      env:
        PNAME: ${{ inputs.pname }}
        CONFIG: ${{ inputs.config }}
      run: |
        if [[ -f "$CONFIG" ]]; then
          json=$("${{ github.action_path }}/../../../check-skip.bash" --pname "$PNAME" --service "nixpkgs-update" --config "$CONFIG")
          skipped=$(echo "$json" | jq -r .skip)
          if [[ "$skipped" == "true" ]]; then
             echo "Skipping $PNAME for nixpkgs-update. Reason: $(echo "$json" | jq -r .reason)"
             echo "should_skip=true" >> "$GITHUB_OUTPUT"
          fi
        fi

    - name: Run nixpkgs-update-log-checker
      if: steps.check-skip.outputs.should_skip != 'true'
      shell: bash
      env:
        PNAME: ${{ inputs.pname }}
      run: |
        nix run 'github:kachick/nixpkgs-update-log-checker' -- --packages "$PNAME"
