name: CI Test Runner Logic
on:
  pull_request:
    paths:
      - '.github/workflows/health-check.yml'
      - '.github/workflows/ci-test-skip.yml'
      - '.github/actions/**'

permissions:
  contents: read

jobs:
  test-skip-hydra:
    name: Verify runner can skip hydra via flag
    uses: ./.github/workflows/health-check.yml
    with:
      pname: 'hello'
      hydra: false
      nixpkgs-update: true

  test-run-all:
    name: Verify runner can execute all services
    uses: ./.github/workflows/health-check.yml
    with:
      pname: 'biz-ud-gothic'
      hydra: true
      nixpkgs-update: true
