name: 🐶 (Interests)

on:
  schedule:
    # Every 11:42 JST
    - cron: '42 2 * * *'
  pull_request:
    types: [labeled]
  workflow_dispatch:

concurrency:
  group: dogfood-health-check
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  check:
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-interests-check'))
    uses: $/.github/workflows/health-check.yml
    with:
      pnames: '["fishnet", "lichess-bot", "stockfish", "systemd-lsp"]'
      config: 'nixpkgs-health-check-by-maintainer.toml'
