name: 'Nixpkgs health checks'
on:
  workflow_call:
    inputs:
      pname:
        required: true
        type: string
      config:
        required: false
        type: string
        default: 'nixpkgs-health-check.toml'
    outputs:
      hydra_skipped:
        description: 'Whether hydra check was skipped'
        value: ${{ jobs.check.outputs.hydra_skipped }}
      nixpkgs_update_skipped:
        description: 'Whether nixpkgs-update check was skipped'
        value: ${{ jobs.check.outputs.nixpkgs_update_skipped }}

defaults:
  run:
    shell: bash

jobs:
  check:
    name: ${{ matrix.service }}
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        service: [hydra, nixpkgs-update]
    outputs:
      # These will be concatenated by GHA when matrix is used
      # but we need to pick specific one for the workflow output
      hydra_skipped: ${{ steps.save-hydra-output.outputs.skipped }}
      nixpkgs_update_skipped: ${{ steps.save-update-output.outputs.skipped }}
    steps:
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          # Enable accept-flake-config for using the garnix
          extra_nix_config: |
            sandbox = true
            accept-flake-config = true
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./
        id: action
        with:
          pname: ${{ inputs.pname }}
          service: ${{ matrix.service }}
          config: ${{ inputs.config }}
      - name: Save hydra output
        id: save-hydra-output
        if: matrix.service == 'hydra'
        env:
          SKIPPED: ${{ steps.action.outputs.should_skip }}
        run: |
          echo "skipped=$SKIPPED" >> "$GITHUB_OUTPUT"
      - name: Save update output
        id: save-update-output
        if: matrix.service == 'nixpkgs-update'
        env:
          SKIPPED: ${{ steps.action.outputs.should_skip }}
        run: |
          echo "skipped=$SKIPPED" >> "$GITHUB_OUTPUT"
