name: health-check-by-maintainer

on:
  workflow_dispatch:
    inputs:
      maintainer:
        description: 'Maintainer ID of the package'
        required: true
        type: string
        default: 'kachick'
      config:
        description: 'Path to the configuration file for skipping checks'
        required: true
        type: string
        default: 'nixpkgs-health-check-by-maintainer.toml'
  workflow_call:
    inputs:
      maintainer:
        description: 'Maintainer ID of the package'
        required: true
        type: string
        default: 'kachick'
      config:
        description: 'Path to the configuration file for skipping checks'
        required: true
        type: string
        default: 'nixpkgs-health-check-by-maintainer.toml'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  check:
    uses: ./.github/workflows/health-check-by-list.yml
    with:
      maintainer: ${{ inputs.maintainer }}
      config: ${{ inputs.config }}
