name: health-check

on:
  workflow_dispatch:
    inputs:
      pnames:
        description: 'JSON array of package names'
        required: true
        type: string
      config:
        description: 'Path to the configuration file for skipping checks'
        required: true
        type: string
        default: 'nixpkgs-health-check-by-maintainer.toml'
  workflow_call:
    inputs:
      pnames:
        description: 'JSON array of package names'
        required: true
        type: string
      config:
        description: 'Path to the configuration file for skipping checks'
        required: true
        type: string
        default: 'nixpkgs-health-check-by-maintainer.toml'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  plan:
    runs-on: ubuntu-24.04
    outputs:
      matrix: '${{ steps.plan.outputs.matrix }}'
    steps:
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: 'nixpkgs=channel:nixpkgs-unstable'
          extra_nix_config: |
            sandbox = true
            accept-flake-config = true
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Checkout health-check scripts
        uses: actions/checkout@v6
        with:
          repository: kachick/nixpkgs-health-check-action
          path: .health-check-action
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false
      - name: Plan execution
        id: plan
        uses: ./.github/actions/plan
        with:
          pnames: ${{ inputs.pnames }}
          config: ${{ inputs.config }}

  check:
    needs: [plan]
    if: fromJson(needs.plan.outputs.matrix)[0] != null
    name: ${{ matrix.item.pname }} / ${{ matrix.item.service }}
    strategy:
      fail-fast: false
      matrix:
        item: '${{ fromJson(needs.plan.outputs.matrix) }}'
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: 'nixpkgs=channel:nixpkgs-unstable'
          extra_nix_config: |
            sandbox = true
            accept-flake-config = true
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run hydra check
        if: matrix.item.service == 'hydra'
        uses: ./.github/actions/hydra
        with:
          pname: ${{ matrix.item.pname }}

      - name: Run update check
        if: matrix.item.service == 'nixpkgs-update'
        uses: ./.github/actions/nixpkgs-update
        with:
          pname: ${{ matrix.item.pname }}
