name: health-check-maintainer

on:
  workflow_dispatch:
    inputs:
      maintainer:
        description: 'Maintainer ID of the package'
        required: true
        type: string
        default: 'kachick'
      config:
        description: 'Path to the configuration file for skipping checks'
        required: true
        type: string
        default: 'nixpkgs-health-check.toml'
  workflow_call:
    inputs:
      maintainer:
        description: 'Maintainer ID of the package'
        required: true
        type: string
        default: 'kachick'
      config:
        description: 'Path to the configuration file for skipping checks'
        required: true
        type: string
        default: 'nixpkgs-health-check.toml'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  get-pnames:
    runs-on: ubuntu-24.04
    env:
      MAINTAINER: ${{ inputs.maintainer }}
    outputs:
      json: '${{ steps.print-pnames-as-json.outputs.json }}'
    steps:
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: 'nixpkgs=channel:nixpkgs-unstable'
          extra_nix_config: |
            sandbox = true
            accept-flake-config = true
      - id: print-pnames-as-json
        run: |
          {
            echo 'json<<JSON'
            nix run github:kachick/nixpkgs-maintained-by -- -id "$MAINTAINER" -json
            echo 'JSON'
          } | tee --append "$GITHUB_OUTPUT"

  check:
    needs: [get-pnames]
    strategy:
      fail-fast: false
      matrix:
        pname: '${{ fromJson(needs.get-pnames.outputs.json) }}'
    uses: ./.github/workflows/health-check-package.yml
    with:
      pname: '${{ matrix.pname }}'
      config: ${{ inputs.config }}
