name: PR Maintainer check

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  check:
    if: contains(github.event.pull_request.labels.*.name, 'run-maintainer-check')
    uses: ./.github/workflows/by-maintainer.yml
    with:
      maintainer: 'kachick'
      config: 'nixpkgs-health-check.toml'
