name: 💨

on:
  pull_request:
    paths:
      - '.github/workflows/health-check.yml'
      - '.github/workflows/smoke.yml'
      - 'action.yml'
      - 'check-skip.*'
      - 'nixpkgs-health-check-by-maintainer.toml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke-test:
    name: 💨 smoke test
    uses: ./.github/workflows/health-check.yml
    with:
      # Use minimum set of packages to verify both skip and execution logic
      pnames: '["hello", "biz-ud-gothic"]'
      config: 'nixpkgs-health-check-by-maintainer.toml'
